# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'caseStudies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'StarWars', '~> 2.0'
  # Pods for caseStudies

end
